language: java
matrix:
  include:
    - name: "Linux JDK8"
      os: linux
      dist: trusty
      jdk:
        - openjdk8
      env:
        - TRAVIS_DIST_NAME="trusty"
    - name: "MacOS JDK8"
      os: osx
      osx_image: xcode9.3
#    - name: "Windows" --- Not yet supported
#      os: windows
#      jdk:
#        - openjdk8

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rm -f '/usr/local/include/c++'; brew install ant; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install ant -y; fi

install:
  - WD=$PWD
  - cd ..
  - git clone https://github.com/Funz/funz-profile
  - cd $WD

script: 
  - ant test

before_deploy:
  - ant clean dist
  - cd dist; zip -r ../plugin-moret.zip *; cd ..
  - ant install
  - zip -r Funz-moret.zip Funz-moret
  
deploy:
  provider: releases
  api_key:
    secure: wKAADBeV98g1fZ7b4Gt+8usIR/ylsDTbl6TWrRHsAqTfPlrNzUpdHp0HIH2u9QF+aWz9gdbZR5wrtkNw82gDDqUqEOIaCrt37YUTNxB3d0y+KZfQ5LucV74uNvXXLvk1BI66ZlzbT8n/uKVVTjdw7IPOo4dlYoj4CIIisrjvU+JT5y+AP47oiamUjOQMUGc2K7JeVxk
gY1HBg3bal8P1mqhCyorgYncZrqBw6ibGQq75gsExWfCMRAwrgkOIC+feLwxig8XsfMmgaKbEJpC+7C6ZxmvZ111gBlZBP1XH/zxqdWeKND3cmrKhUPTIfHekVam6BAWitSPKbWxZLFJudGhIpaQeN1ZBzlMWsz9YyddkVHVMROkUm9hb7d5bBTdUnuW2A1dtVnLEg+GMcfUyJOuwnE
/JiYHQNevmoKsu6k8jWTvaaTBWhhB5uVubtwf79BpOLoF2LF933R0FI0EsJm2IkVOeROS0qouvsSZyAkoP5JZQ3Y4kj627FgN8CJxEBgXmqgTohfO30JVKzsU07+p1F+yo/Gl0HkafnHiVq1m/6Wb0uLSfZ7CS8tWe3EqG/VQl9NJj0mH1UHTYQX5M5TyMhfhxyL46pn36jVRcPnrpw
11GDfTd1/AqsFgeVEXcyIlpd1ZnC+woP5no0hbfEvC4a8PEQSTce6LgJWETTJo=
  file_glob: true
  file:
    - Funz-*.zip
    - plugin-*.zip
  on:
    tags: true
    branch: master
  skip_cleanup: true
  overwrite: true
